#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_FILES = [
    "README.md",
    "REPRODUCE.md",
    "IMPROVEMENT_CHANGELOG.md",
    "requirements.txt",
    "docs/PROBLEM.md",
    "docs/EVALUATION.md",
    "docs/PHASE_4_RESULT.md",
    "docs/SUBMISSION_CHECKLIST.md",
    "docs/VIDEO_PLAN.md",
    "benchmark/cases.json",
    "benchmark/oracles.py",
    "benchmark/reference_repairs.py",
    "benchmark/public_context.py",
    "scripts/validate_benchmark.py",
    "scripts/smoke_benchmark.py",
    "scripts/run_phase5.py",
    "scripts/aggregate_phase5.py",
    "scripts/run_incident.py",
]

PHASE5_SYSTEMS = [
    "context-baseline",
    "driftdoctor-no-review",
    "driftdoctor-review",
]


def fail(message: str, failures: list[str]) -> None:
    failures.append(message)
    print(f"FAIL: {message}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit DriftDoctor submission readiness.")
    parser.add_argument(
        "--require-phase5",
        action="store_true",
        help="Require complete checked-in Phase 5 evidence for all three comparison systems.",
    )
    args = parser.parse_args()
    failures: list[str] = []

    print("Submission file audit")
    for relative in REQUIRED_FILES:
        path = ROOT / relative
        if path.is_file():
            print(f"OK: {relative}")
        else:
            fail(f"missing required file: {relative}", failures)

    cases_path = ROOT / "benchmark" / "cases.json"
    if cases_path.is_file():
        cases = json.loads(cases_path.read_text()).get("cases", [])
        if len(cases) != 12:
            fail(f"benchmark must contain 12 cases, found {len(cases)}", failures)
        challenge = [case for case in cases if case.get("challenge_case")]
        if len(challenge) != 1:
            fail(f"expected exactly one challenge case, found {len(challenge)}", failures)
        if not all(case.get("oracle_checks") for case in cases):
            fail("every case must declare oracle checks", failures)

    print("\nPhase 5 evidence audit")
    phase5_root = ROOT / "benchmark" / "results" / "phase5"
    summaries_found = 0
    for system in PHASE5_SYSTEMS:
        path = phase5_root / system / "summary.json"
        if not path.is_file():
            if args.require_phase5:
                fail(f"{system} summary is missing from final checked-in evidence", failures)
            else:
                print(f"PENDING: {system} summary is not checked into this branch")
            continue
        summaries_found += 1
        data = json.loads(path.read_text())
        if data.get("complete") is not True:
            fail(f"{system} result is incomplete", failures)
        if data.get("expected_cases") != 12 or data.get("scored_cases") != 12:
            fail(f"{system} must score exactly 12/12 cases", failures)
        if data.get("infrastructure_errors"):
            fail(f"{system} contains infrastructure errors", failures)
        if data.get("verified_resolution_rate") is None:
            fail(f"{system} has no publishable VRR", failures)

    if summaries_found == 0 and not args.require_phase5:
        print("INFO: Phase 5 result artifacts are generated by CI and are not required to be committed during the pending-measurement stage.")

    print("\nClaim hygiene audit")
    readme = (ROOT / "README.md").read_text(errors="replace") if (ROOT / "README.md").exists() else ""
    forbidden = ["100% success", "perfect accuracy", "solves all incidents"]
    for phrase in forbidden:
        if phrase.lower() in readme.lower():
            fail(f"README contains unverified absolute claim: {phrase!r}", failures)

    if failures:
        print(f"\nSubmission preflight failed with {len(failures)} issue(s).")
        return 1
    print("\nSubmission preflight passed for all currently available evidence.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
